### ISSUE TITLE
Random-Encounters | about-time [Event Time not increasing event reschedule rejected

### ISSUE THREAD

**Issue by k7755g** [veevelder/random-encounters#4]
Upon saving an encounter with a roll-table and a 'room', when a character token enters an encounter area, the following error appears and nothing else happens.

To what I can see, it seems to be calling a empty encounter some where.

![error1](https://user-images.githubusercontent.com/6447410/189825184-c9a0b182-6d19-4414-b4eb-ad910263f06a.png)
![error2](https://user-images.githubusercontent.com/6447410/189825196-3552107e-3ea3-4e28-a8a8-ce03a666cf0b.png)

**Comment by veevelder** [comment]
I will take a look at it

**Comment by veevelder** [comment]
I think I have fixed the issue in the new update, you may have to re-save the encounters to make the error go away. Let me know if it works for you.

**Comment by k7755g** [comment]
It fixed the error that appears when a token enters a room, but it still does not roll the table & it appears not save to unless you place at least a '1' in the Time option, but still no roll attempted after 1 minute.

It may have to do with about-time & simple calendars API updates. ( see attached )
![error3](https://user-images.githubusercontent.com/6447410/190999114-15914660-faa0-4cb1-8069-51d11344ce89.png)

**Comment by veevelder** [comment]
Sorry for the delay, but in order to use the about-time functionality you need at least some time interval and it will run every minute from the time you saved it and not on the minute. For example if you saved it at 12:27:22 it will run 12:28:22. If you want it to run every minute on the minute I can look into that, like 12:27:22 is when you saved it will run 12:28:00. Regardless I will look into the warnings you posted

**Comment by veevelder** [comment]
sorry for the long delay, but I did fix those warnings and another annoying bug which may fix some of your issues, if you want to take a look at [this](https://github.com/veevelder/random-encounters/blob/main/about-time-issues.md), it may solve some of your issues. Let me know if this works or if you have other questions

**Comment by veevelder** [comment]
closing due to inactivity
